### ISSUE TITLE
`SWTException: Invalid thread access` on OSX

### ISSUE THREAD

**Issue by phinze** [ashbb/purple_shoes#1]
Hey ashbb!

Cool stuff you got going on here!  I've just stopped by to report my experience testing this on OSX 10.7.

Here's what I did to get things started, rvm style.

``` bash
git clone https://github.com/ashbb/purple_shoes.git
cd purple_shoes
echo "rvm jruby@purple_shoes --create" > .rvmrc
cd . # get rvm to pick up rvmrc and create gemset
gem install swt
cd samples/
jruby --1.9 sample.rb
```

And here's the output I get:

```
objc[18116]: Object 0x7fbc9203c8c0 of class __NSArrayM autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
***WARNING: Display must be created on main thread due to Cocoa restrictions.
NativeException: org.eclipse.swt.SWTException: Invalid thread access
     app at /Users/phinze/dev/purple_shoes/lib/shoes/main.rb:15
  (root) at sample1.rb:6
```

Googling for "Display must be created on main thread due to Cocoa restrictions.", I found recommendations to try adding `-XstartOnFirstThread` as a JVM arg.  I tried sticking this onto the jruby arguments--as it seems to have support for `-X` options--but I got the exact same output.

The SWT FAQ does have an entry on this exception, though I haven't yet delved deep enough to figure out how that answer might apply here:

http://www.eclipse.org/swt/faq.php#uithread

So there's a bit of OSX testing for you.  Sorry I couldn't report better news!  Hopefully we can figure out what's going on here and it'll be smooth sailing after that.

**Comment by ashbb** [comment]
Hi Paul,

Thank you for taking your time testing Purple Shoes on OSX!!

I don't have any solutions for now, sorry. But at first, could you try to run the following snippet?

<pre>
  require 'java'
  require 'swt'
  class Object
    include_package 'org.eclipse.swt'
    include_package 'org.eclipse.swt.widgets'
  end
  display = Display.new
  shell = Shell.new display
  shell.setSize 300, 300
  shell.open
  while !shell.isDisposed do
    display.sleep unless display.readAndDispatch
  end
  display.dispose
</pre>


ashbb

**Comment by phinze** [comment]
Looks like the exact same error shows up on the line `display = Display.new`...

AH HA!  I made my way over to the swt gem homepage and discovered I was using the wrong flag to pass jvm option to jruby.

So if I run the above or any of samples you currently have working like so:

```
jruby -J-XstartOnFirstThread --1.9 sample1.rb
```

...then everything works wonderfully!

Will fork to add this note to the README.

**Comment by ashbb** [comment]
> then everything works wonderfully!

Wow, you got the solution. Awesome!

> Will fork to add this note to the README.

Thanks. I'll be waiting. :)

**Comment by phinze** [comment]
Oh and for the record, since we'll probably eventually want to think about nicer cross-platform handling of this issue, here's a good thread with relevant info and links.

http://stackoverflow.com/questions/3976342/running-swt-based-cross-platform-jar-properly-on-a-mac
